global:
  scrape_interval: 15s

  external_labels:
    monitor: "prometheus-monitoring"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

rule_files:
  - /etc/alertmanager/alert.rules

scrape_configs:
  - job_name: "Prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "Dynamic"
    file_sd_configs:
      - files:
          - targets.json
